Repository brenocq/implot3d, pull requests merged in 2024-12, with the labels that each got.

#11 Fix compiler issues / replace std::sin with ImSin ... / Add IMPLOT3D_…
  implot3d.cpp
  implot3d.h
  implot3d_demo.cpp
  implot3d_internal.h
  implot3d_items.cpp
Labels: type:chore, prio:high, status:review

#8 Add a github-ci script to test compilation on Linux, macOS and Windows
  .github/workflows/main.yml
Labels: type:chore, prio:medium, status:review

#7 Minimal changes needed to make the example build and run on macOS
  example/main.cpp
Labels: type:bug, prio:high, status:review
