Repository brenocq/implot3d, pull requests merged in 2025-03, with the labels that each got.

#73 Add an integer encoded version number (`IMPLOT3D_VERSION_NUM`)
  implot3d.h
Labels: type:chore, prio:medium, status:review

#75 Fix division by zero in ImRemap01 function
  implot3d_internal.h
Labels: type:bug, prio:high, status:done

#80 Consider axis inversion before calculating Z position for Z-order
  implot3d_items.cpp
Labels: type:bug, prio:high, status:review
