Repository brenocq/implot3d, pull requests merged in 2025-01, with the labels that each got.

#43 Implot demo: add link in the readme (+ minor warning fix)
  README.md
  implot3d.cpp
Labels: type:docs, prio:medium, status:review

#46 Box scaling (custom aspect ratios)
  implot3d.cpp
  implot3d.h
  implot3d_demo.cpp
  implot3d_internal.h
Labels: type:feat, prio:high, status:done

#53 Fix warnings & README bindings
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  README.md
  implot3d.cpp
  implot3d_demo.cpp
  implot3d_internal.h
  implot3d_items.cpp
Labels: type:chore, prio:medium, status:done

#54 Fix min/max lock & axis transformation
  implot3d.cpp
  implot3d_internal.h
Labels: type:bug, prio:high, status:done

#59 Display avatars in discussion cards
  .github/scripts/update_readme/update_readme.py
Labels: prio:low, type:chore, status:done

#56 Add common IDE cache folders to gitignored
  .gitignore
Labels: type:chore, prio:medium, status:review

#60 Fix auto fit giggle
  implot3d.cpp
  implot3d_internal.h
Labels: type:bug, prio:low, status:done

#55 Add SetupAxisTicks for configuring custom ticks
  implot3d.cpp
  implot3d.h
  implot3d_demo.cpp
  implot3d_internal.h
Labels: type:feat, prio:medium, status:review
